"""Add BalanceTopUp model final fix v2

Revision ID: 0833acce9df1
Revises: c14a2b0da1d1
Create Date: 2026-04-08 16:23:10.637064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0833acce9df1'
down_revision: Union[str, Sequence[str], None] = 'c14a2b0da1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_top_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_org_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['med_org_id'], ['medicalorganization.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_top_up_id'), 'balance_top_up', ['id'], unique=False)
    op.create_index(op.f('ix_balance_top_up_med_org_id'), 'balance_top_up', ['med_org_id'], unique=False)
    op.add_column('payment', sa.Column('med_org_id', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('top_up_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payment_med_org_id'), 'payment', ['med_org_id'], unique=False)
    op.create_foreign_key(None, 'payment', 'medicalorganization', ['med_org_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'balance_top_up', ['top_up_id'], ['id'])
    op.add_column('reservationitem', sa.Column('production_price', sa.Float(), nullable=True))
    op.add_column('reservationitem', sa.Column('other_expenses', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationitem', 'other_expenses')
    op.drop_column('reservationitem', 'production_price')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_index(op.f('ix_payment_med_org_id'), table_name='payment')
    op.drop_column('payment', 'top_up_id')
    op.drop_column('payment', 'med_org_id')
    op.drop_index(op.f('ix_balance_top_up_med_org_id'), table_name='balance_top_up')
    op.drop_index(op.f('ix_balance_top_up_id'), table_name='balance_top_up')
    op.drop_table('balance_top_up')
    # ### end Alembic commands ###
