"""rename description to notes in visitplan

Revision ID: 0fc2ae710b9b
Revises: 8c9d0a1b2c3d
Create Date: 2026-04-01 11:42:21.057284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc2ae710b9b'
down_revision: Union[str, Sequence[str], None] = '8c9d0a1b2c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userloginhistory', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('userloginhistory', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # Rename column description to notes
    op.alter_column('visitplan', 'description', new_column_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column notes back to description
    op.alter_column('visitplan', 'notes', new_column_name='description')
    op.alter_column('userloginhistory', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('userloginhistory', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
