"""Add Visit and VisitPlan models

Revision ID: 1e7c2eddac70
Revises: b5c564431fd3
Create Date: 2026-02-11 20:01:27.382791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7c2eddac70'
down_revision: Union[str, Sequence[str], None] = 'b5c564431fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_rep_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('visit_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['med_rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_id'), 'visit', ['id'], unique=False)
    op.create_table('visitplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_rep_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visit_type', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['med_rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitplan_id'), 'visitplan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitplan_id'), table_name='visitplan')
    op.drop_table('visitplan')
    op.drop_index(op.f('ix_visit_id'), table_name='visit')
    op.drop_table('visit')
    # ### end Alembic commands ###
