"""add_inn_to_med_org

Revision ID: 549505de8a4a
Revises: 0518f45c02be
Create Date: 2026-03-03 17:35:45.382543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549505de8a4a'
down_revision: Union[str, Sequence[str], None] = '0518f45c02be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalorganization', sa.Column('inn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicalorganization', 'inn')
    # ### end Alembic commands ###
