"""Add BalanceTopUp and tracking v5

Revision ID: c14a2b0da1d1
Revises: c1bbbdf4e768
Create Date: 2026-04-08 16:21:09.599930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14a2b0da1d1'
down_revision: Union[str, Sequence[str], None] = 'c1bbbdf4e768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationitem', 'other_expenses')
    op.drop_column('reservationitem', 'production_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservationitem', sa.Column('production_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('reservationitem', sa.Column('other_expenses', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
