"""Add returned_quantity

Revision ID: eb69b77fbfec
Revises: 549505de8a4a
Create Date: 2026-03-04 06:23:48.019455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb69b77fbfec'
down_revision: Union[str, Sequence[str], None] = '549505de8a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservationitem', sa.Column('returned_quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationitem', 'returned_quantity')
    # ### end Alembic commands ###
