"""update_visit_plan_add_notification

Revision ID: f3794cff8006
Revises: b265b8754ad6
Create Date: 2026-02-13 16:55:32.641044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3794cff8006'
down_revision: Union[str, Sequence[str], None] = 'b265b8754ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.add_column('visitplan', sa.Column('med_org_id', sa.Integer(), nullable=True))
    op.add_column('visitplan', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('visitplan', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'visitplan', 'medicalorganization', ['med_org_id'], ['id'])
    op.drop_column('visitplan', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitplan', sa.Column('is_completed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visitplan', type_='foreignkey')
    op.alter_column('visitplan', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('visitplan', 'status')
    op.drop_column('visitplan', 'med_org_id')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
