"""add_med_org_stock

Revision ID: 0518f45c02be
Revises: e9f34468db7a
Create Date: 2026-03-03 15:55:10.013680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0518f45c02be'
down_revision: Union[str, Sequence[str], None] = 'e9f34468db7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_org_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_org_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['med_org_id'], ['medicalorganization.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_med_org_stock_id'), 'med_org_stock', ['id'], unique=False)
    op.create_index(op.f('ix_unassigned_sale_id'), 'unassigned_sale', ['id'], unique=False)
    op.create_index(op.f('ix_unassigned_sale_invoice_id'), 'unassigned_sale', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_unassigned_sale_med_rep_id'), 'unassigned_sale', ['med_rep_id'], unique=False)
    op.create_index(op.f('ix_unassigned_sale_product_id'), 'unassigned_sale', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unassigned_sale_product_id'), table_name='unassigned_sale')
    op.drop_index(op.f('ix_unassigned_sale_med_rep_id'), table_name='unassigned_sale')
    op.drop_index(op.f('ix_unassigned_sale_invoice_id'), table_name='unassigned_sale')
    op.drop_index(op.f('ix_unassigned_sale_id'), table_name='unassigned_sale')
    op.drop_index(op.f('ix_med_org_stock_id'), table_name='med_org_stock')
    op.drop_table('med_org_stock')
    # ### end Alembic commands ###
