"""add_other_expenses_to_product

Revision ID: 1f80e5f8601b
Revises: d5045968d276
Create Date: 2026-02-25 21:32:38.477926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f80e5f8601b'
down_revision: Union[str, Sequence[str], None] = 'd5045968d276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('other_expenses', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'other_expenses')
    # ### end Alembic commands ###
