"""add product_id to bonus_ledger

Revision ID: 3ffaff6875cc
Revises: 5e5565fd1572
Create Date: 2026-03-06 15:09:49.195628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffaff6875cc'
down_revision: Union[str, Sequence[str], None] = '5e5565fd1572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_ledger', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bonus_ledger', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bonus_ledger', type_='foreignkey')
    op.drop_column('bonus_ledger', 'product_id')
    # ### end Alembic commands ###
