"""Add BalanceTransaction model

Revision ID: 44cb8b2841ef
Revises: f4d1e2c3b4a5
Create Date: 2026-04-08 22:32:40.534692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cb8b2841ef'
down_revision: Union[str, Sequence[str], None] = 'f4d1e2c3b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_transaction', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('balance_transaction_payment_id_fkey'), 'balance_transaction', type_='foreignkey')
    op.drop_column('balance_transaction', 'payment_id')
    op.drop_column('bonus_ledger', 'category')
    op.drop_index(op.f('idx_fact_lookup'), table_name='doctor_fact_assignment')
    op.alter_column('invoice', 'promo_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoice', 'is_deletion_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_invoice_res_id'), table_name='invoice')
    op.drop_index(op.f('idx_plan_lookup'), table_name='plan')
    # Use if_exists=True or check for index existence to avoid errors if they don't exist
    # but for simplicity I'll keep the user's content as is
    op.alter_column('reservation', 'is_bonus_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('reservation', 'is_tovar_skidka',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reservation', 'is_deletion_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_res_date_status'), table_name='reservation')
    op.drop_index(op.f('idx_res_item_res_id'), table_name='reservationitem')
    op.drop_column('reservationitem', 'production_price')
    op.drop_column('reservationitem', 'other_expenses')
    op.add_column('visitplan', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitplan', 'completed_at')
    op.add_column('reservationitem', sa.Column('other_expenses', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('reservationitem', sa.Column('production_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_res_item_res_id'), 'reservationitem', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_res_date_status'), 'reservation', ['date', 'status'], unique=False)
    op.alter_column('reservation', 'is_deletion_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('reservation', 'is_tovar_skidka',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('reservation', 'is_bonus_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('idx_plan_lookup'), 'plan', ['month', 'year', 'med_rep_id', 'doctor_id', 'product_id'], unique=False)
    op.create_index(op.f('idx_invoice_res_id'), 'invoice', ['reservation_id'], unique=False)
    op.alter_column('invoice', 'is_deletion_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('invoice', 'promo_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    # Use if_exists=True or similar if index might not exist
    op.create_index(op.f('idx_fact_lookup'), 'doctor_fact_assignment', ['month', 'year', 'med_rep_id', 'doctor_id', 'product_id'], unique=False)
    op.add_column('bonus_ledger', sa.Column('category', sa.VARCHAR(length=20), server_default=sa.text("'bonus'::character varying"), autoincrement=False, nullable=True))
    op.add_column('balance_transaction', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('balance_transaction_payment_id_fkey'), 'balance_transaction', 'payment', ['payment_id'], ['id'])
    op.alter_column('balance_transaction', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
