"""add_lat_lng_to_med_org

Revision ID: 562da99303f9
Revises: ac4a79be652c
Create Date: 2026-03-08 20:31:25.303391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562da99303f9'
down_revision: Union[str, Sequence[str], None] = 'ac4a79be652c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalorganization', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('medicalorganization', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicalorganization', 'longitude')
    op.drop_column('medicalorganization', 'latitude')
    # ### end Alembic commands ###
