"""add marketing_amount to reservation_item

Revision ID: 595d6ab2cd25
Revises: 562da99303f9
Create Date: 2026-03-12 22:35:41.266521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595d6ab2cd25'
down_revision: Union[str, Sequence[str], None] = '562da99303f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservationitem', sa.Column('marketing_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationitem', 'marketing_amount')
    # ### end Alembic commands ###
