"""Add target_month and target_year to bonus_ledger

Revision ID: 5e5565fd1572
Revises: 69d2bff5c543
Create Date: 2026-03-05 21:28:04.788602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5565fd1572'
down_revision: Union[str, Sequence[str], None] = '69d2bff5c543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_ledger', sa.Column('target_month', sa.Integer(), nullable=True))
    op.add_column('bonus_ledger', sa.Column('target_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus_ledger', 'target_year')
    op.drop_column('bonus_ledger', 'target_month')
    # ### end Alembic commands ###
