"""Add contact_phone to MedicalOrganization

Revision ID: 6133610a5087
Revises: dd8799bbb1b8
Create Date: 2026-02-21 23:37:19.046597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6133610a5087'
down_revision: Union[str, Sequence[str], None] = 'dd8799bbb1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalorganization', sa.Column('contact_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicalorganization', 'contact_phone')
    # ### end Alembic commands ###
