"""Add nds_percent to reservation

Revision ID: 69d2bff5c543
Revises: eb69b77fbfec
Create Date: 2026-03-04 06:40:16.017354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d2bff5c543'
down_revision: Union[str, Sequence[str], None] = 'eb69b77fbfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('nds_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'nds_percent')
    # ### end Alembic commands ###
