"""Add CRM module tables

Revision ID: 6cac4735e0d3
Revises: 8dd13e6024a7
Create Date: 2026-02-10 22:21:26.049947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cac4735e0d3'
down_revision: Union[str, Sequence[str], None] = '8dd13e6024a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctorcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctorcategory_id'), 'doctorcategory', ['id'], unique=False)
    op.create_index(op.f('ix_doctorcategory_name'), 'doctorcategory', ['name'], unique=True)
    op.create_table('doctorspecialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctorspecialty_id'), 'doctorspecialty', ['id'], unique=False)
    op.create_index(op.f('ix_doctorspecialty_name'), 'doctorspecialty', ['name'], unique=True)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_id'), 'region', ['id'], unique=False)
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.create_table('medicalorganization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicalorganization_id'), 'medicalorganization', ['id'], unique=False)
    op.create_index(op.f('ix_medicalorganization_name'), 'medicalorganization', ['name'], unique=False)
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('med_org_id', sa.Integer(), nullable=True),
    sa.Column('assigned_rep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_rep_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['doctorcategory.id'], ),
    sa.ForeignKeyConstraint(['med_org_id'], ['medicalorganization.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['doctorspecialty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_full_name'), 'doctor', ['full_name'], unique=False)
    op.create_index(op.f('ix_doctor_id'), 'doctor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_full_name'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_medicalorganization_name'), table_name='medicalorganization')
    op.drop_index(op.f('ix_medicalorganization_id'), table_name='medicalorganization')
    op.drop_table('medicalorganization')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_index(op.f('ix_region_id'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_doctorspecialty_name'), table_name='doctorspecialty')
    op.drop_index(op.f('ix_doctorspecialty_id'), table_name='doctorspecialty')
    op.drop_table('doctorspecialty')
    op.drop_index(op.f('ix_doctorcategory_name'), table_name='doctorcategory')
    op.drop_index(op.f('ix_doctorcategory_id'), table_name='doctorcategory')
    op.drop_table('doctorcategory')
    # ### end Alembic commands ###
