"""Add return approval flow fields

Revision ID: 94f1fad74dc6
Revises: 595d6ab2cd25
Create Date: 2026-03-13 15:53:00.958788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f1fad74dc6'
down_revision: Union[str, Sequence[str], None] = '595d6ab2cd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('is_return_pending', sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column('reservationitem', sa.Column('return_requested_quantity', sa.Integer(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationitem', 'return_requested_quantity')
    op.drop_column('reservation', 'is_return_pending')
    # ### end Alembic commands ###
