"""add is_paid to bonus_ledger

Revision ID: a1df8a97c047
Revises: 3ffaff6875cc
Create Date: 2026-03-06 22:39:05.784233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1df8a97c047'
down_revision: Union[str, Sequence[str], None] = '3ffaff6875cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable first
    op.add_column('bonus_ledger', sa.Column('is_paid', sa.Boolean(), nullable=True))
    
    # 2. Update existing ACCRUALs to be paid so existing balances don't reset to 0
    op.execute("UPDATE bonus_ledger SET is_paid = true WHERE ledger_type = 'accrual'")
    
    # 3. Update all others (OFFSET, ADVANCE) to false as default
    op.execute("UPDATE bonus_ledger SET is_paid = false WHERE is_paid IS NULL")
    
    # 4. Alter column to not null
    op.alter_column('bonus_ledger', 'is_paid', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus_ledger', 'is_paid')
    # ### end Alembic commands ###
