"""add_bonus_payment_table

Revision ID: a92c6ee8f2db
Revises: 63513bc4d875
Create Date: 2026-02-24 09:00:52.495365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92c6ee8f2db'
down_revision: Union[str, Sequence[str], None] = '63513bc4d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_rep_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('for_month', sa.Integer(), nullable=False),
    sa.Column('for_year', sa.Integer(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['med_rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_payment_id'), 'bonus_payment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonus_payment_id'), table_name='bonus_payment')
    op.drop_table('bonus_payment')
    # ### end Alembic commands ###
