"""Add amount to DoctorFactAssignment

Revision ID: ac4a79be652c
Revises: e2cf183abad9
Create Date: 2026-03-08 12:55:36.666807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4a79be652c'
down_revision: Union[str, Sequence[str], None] = 'e2cf183abad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_fact_assignment', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_fact_assignment', 'amount')
    # ### end Alembic commands ###
