"""Add Doctor fields

Revision ID: b265b8754ad6
Revises: 1e7c2eddac70
Create Date: 2026-02-11 20:15:39.309195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b265b8754ad6'
down_revision: Union[str, Sequence[str], None] = '1e7c2eddac70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('contact1', sa.String(), nullable=True))
    op.add_column('doctor', sa.Column('contact2', sa.String(), nullable=True))
    op.add_column('doctor', sa.Column('email', sa.String(), nullable=True))
    op.add_column('doctor', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('doctor', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('doctor', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('doctor', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'address')
    op.drop_column('doctor', 'longitude')
    op.drop_column('doctor', 'latitude')
    op.drop_column('doctor', 'birth_date')
    op.drop_column('doctor', 'email')
    op.drop_column('doctor', 'contact2')
    op.drop_column('doctor', 'contact1')
    # ### end Alembic commands ###
