"""Add hierarchical relationships and new roles to User model

Revision ID: b5c564431fd3
Revises: 96a55555c354
Create Date: 2026-02-11 00:21:19.617713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c564431fd3'
down_revision: Union[str, Sequence[str], None] = '96a55555c354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'manager_id')
    # ### end Alembic commands ###
