"""Add salary and accountant models

Revision ID: c1bbbdf4e768
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 22:28:34.504391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bbbdf4e768'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_expense_category_id'), 'expense_category', ['id'], unique=False)
    op.create_table('other_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_expense_date'), 'other_expense', ['date'], unique=False)
    op.create_index(op.f('ix_other_expense_id'), 'other_expense', ['id'], unique=False)
    op.drop_constraint(op.f('bonus_ledger_fact_id_fkey'), 'bonus_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'bonus_ledger', 'doctor_fact_assignment', ['fact_id'], ['id'])
    op.add_column('reservation', sa.Column('is_salary_enabled', sa.Boolean(), nullable=True))
    op.add_column('reservationitem', sa.Column('salary_amount', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uq_role_section'), 'role_permission', type_='unique')
    op.create_index(op.f('ix_role_permission_id'), 'role_permission', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permission_id'), table_name='role_permission')
    op.create_unique_constraint(op.f('uq_role_section'), 'role_permission', ['role', 'section_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('reservationitem', 'salary_amount')
    op.drop_column('reservation', 'is_salary_enabled')
    op.drop_constraint(None, 'bonus_ledger', type_='foreignkey')
    op.create_foreign_key(op.f('bonus_ledger_fact_id_fkey'), 'bonus_ledger', 'doctor_fact_assignment', ['fact_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_other_expense_id'), table_name='other_expense')
    op.drop_index(op.f('ix_other_expense_date'), table_name='other_expense')
    op.drop_table('other_expense')
    op.drop_index(op.f('ix_expense_category_id'), table_name='expense_category')
    op.drop_table('expense_category')
    # ### end Alembic commands ###
