"""add_ledger_category_to_bonus_ledger

Revision ID: c59c0d33c5f7
Revises: f4d1e2c3b4a5
Create Date: 2026-04-17 07:00:32.283474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59c0d33c5f7'
down_revision: Union[str, Sequence[str], None] = 'f4d1e2c3b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_transaction', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    
    # 1. Add column as nullable first
    op.add_column('bonus_ledger', sa.Column('ledger_category', sa.String(), nullable=True))
    
    # 2. Update existing rows with 'salary' if notes contain "Зарплата", else 'bonus'
    op.execute("UPDATE bonus_ledger SET ledger_category = 'salary' WHERE notes LIKE '%Зарплата%'")
    op.execute("UPDATE bonus_ledger SET ledger_category = 'bonus' WHERE ledger_category IS NULL")
    
    # 3. Set NOT NULL constraint
    op.alter_column('bonus_ledger', 'ledger_category', nullable=False)
    
    op.create_index(op.f('ix_bonus_ledger_ledger_category'), 'bonus_ledger', ['ledger_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonus_ledger_ledger_category'), table_name='bonus_ledger')
    op.drop_column('bonus_ledger', 'ledger_category')
    op.alter_column('balance_transaction', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
