"""add_doctor_product_to_bonus_payment

Revision ID: d5045968d276
Revises: a92c6ee8f2db
Create Date: 2026-02-24 21:40:17.100342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5045968d276'
down_revision: Union[str, Sequence[str], None] = 'a92c6ee8f2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_payment', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('bonus_payment', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bonus_payment', 'doctor', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'bonus_payment', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bonus_payment', type_='foreignkey')
    op.drop_constraint(None, 'bonus_payment', type_='foreignkey')
    op.drop_column('bonus_payment', 'product_id')
    op.drop_column('bonus_payment', 'doctor_id')
    # ### end Alembic commands ###
