"""Add is_active to Doctor

Revision ID: dbe2c3bc3ba4
Revises: 5c94a010a422
Create Date: 2026-03-02 09:44:38.090524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe2c3bc3ba4'
down_revision: Union[str, Sequence[str], None] = '5c94a010a422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'is_active')
    # ### end Alembic commands ###
