"""refactor_modules_v3

Revision ID: dd8799bbb1b8
Revises: f3794cff8006
Create Date: 2026-02-20 06:44:24.543390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8799bbb1b8'
down_revision: Union[str, Sequence[str], None] = 'f3794cff8006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medrep_organization',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['medicalorganization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_table('product_manufacturer',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'manufacturer_id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('warehouse_type', sa.String(), nullable=True),
    sa.Column('med_org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['med_org_id'], ['medicalorganization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_id'), 'warehouse', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_name'), 'warehouse', ['name'], unique=True)
    op.create_table('doctor_monthly_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('plan_quantity', sa.Integer(), nullable=True),
    sa.Column('sold_quantity', sa.Integer(), nullable=True),
    sa.Column('paid_quantity', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('bonus_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_monthly_stat_doctor_id'), 'doctor_monthly_stat', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_monthly_stat_id'), 'doctor_monthly_stat', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_monthly_stat_month'), 'doctor_monthly_stat', ['month'], unique=False)
    op.create_index(op.f('ix_doctor_monthly_stat_year'), 'doctor_monthly_stat', ['year'], unique=False)
    op.create_table('warehouse_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_stock_id'), 'warehouse_stock', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_stock_product_id'), 'warehouse_stock', ['product_id'], unique=False)
    op.create_table('warehouse_stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['warehouse_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_stock_movement_id'), 'warehouse_stock_movement', ['id'], unique=False)
    op.create_table('bonus_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ledger_type', sa.String(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['reservationitem.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_ledger_created_at'), 'bonus_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_bonus_ledger_id'), 'bonus_ledger', ['id'], unique=False)
    op.drop_index(op.f('ix_salefact_id'), table_name='salefact')
    op.drop_table('salefact')
    op.add_column('invoice', sa.Column('currency', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.add_column('manufacturer', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('manufacturer', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('medicalorganization_assigned_rep_id_fkey'), 'medicalorganization', type_='foreignkey')
    op.drop_column('medicalorganization', 'assigned_rep_id')
    op.add_column('payment', sa.Column('allocated_doctor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    op.create_foreign_key(None, 'payment', 'doctor', ['allocated_doctor_id'], ['id'])
    op.add_column('plan', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('marketing_expense', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('salary_expense', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('product_manufacturer_id_fkey'), 'product', type_='foreignkey')
    op.drop_column('product', 'marketing_cost')
    op.drop_column('product', 'salary_cost')
    op.drop_column('product', 'manufacturer_id')
    op.drop_column('product', 'status')
    op.add_column('reservation', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservation_status'), 'reservation', ['status'], unique=False)
    op.create_foreign_key(None, 'reservation', 'warehouse', ['warehouse_id'], ['id'])
    op.add_column('reservationitem', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('reservationitem_reservation_id_fkey'), 'reservationitem', type_='foreignkey')
    op.create_foreign_key(None, 'reservationitem', 'manufacturer', ['manufacturer_id'], ['id'])
    op.create_foreign_key(None, 'reservationitem', 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservationitem', type_='foreignkey')
    op.drop_constraint(None, 'reservationitem', type_='foreignkey')
    op.create_foreign_key(op.f('reservationitem_reservation_id_fkey'), 'reservationitem', 'reservation', ['reservation_id'], ['id'])
    op.drop_column('reservationitem', 'manufacturer_id')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_index(op.f('ix_reservation_status'), table_name='reservation')
    op.drop_column('reservation', 'warehouse_id')
    op.add_column('product', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('salary_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('marketing_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('product_manufacturer_id_fkey'), 'product', 'manufacturer', ['manufacturer_id'], ['id'])
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'salary_expense')
    op.drop_column('product', 'marketing_expense')
    op.drop_column('product', 'is_active')
    op.drop_column('plan', 'deadline')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_column('payment', 'allocated_doctor_id')
    op.add_column('medicalorganization', sa.Column('assigned_rep_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('medicalorganization_assigned_rep_id_fkey'), 'medicalorganization', 'user', ['assigned_rep_id'], ['id'])
    op.drop_column('manufacturer', 'updated_at')
    op.drop_column('manufacturer', 'created_at')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_column('invoice', 'currency')
    op.create_table('salefact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('med_rep_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('salefact_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['med_rep_id'], ['user.id'], name=op.f('salefact_med_rep_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('salefact_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('salefact_pkey'))
    )
    op.create_index(op.f('ix_salefact_id'), 'salefact', ['id'], unique=False)
    op.drop_index(op.f('ix_bonus_ledger_id'), table_name='bonus_ledger')
    op.drop_index(op.f('ix_bonus_ledger_created_at'), table_name='bonus_ledger')
    op.drop_table('bonus_ledger')
    op.drop_index(op.f('ix_warehouse_stock_movement_id'), table_name='warehouse_stock_movement')
    op.drop_table('warehouse_stock_movement')
    op.drop_index(op.f('ix_warehouse_stock_product_id'), table_name='warehouse_stock')
    op.drop_index(op.f('ix_warehouse_stock_id'), table_name='warehouse_stock')
    op.drop_table('warehouse_stock')
    op.drop_index(op.f('ix_doctor_monthly_stat_year'), table_name='doctor_monthly_stat')
    op.drop_index(op.f('ix_doctor_monthly_stat_month'), table_name='doctor_monthly_stat')
    op.drop_index(op.f('ix_doctor_monthly_stat_id'), table_name='doctor_monthly_stat')
    op.drop_index(op.f('ix_doctor_monthly_stat_doctor_id'), table_name='doctor_monthly_stat')
    op.drop_table('doctor_monthly_stat')
    op.drop_index(op.f('ix_warehouse_name'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_table('product_manufacturer')
    op.drop_table('medrep_organization')
    # ### end Alembic commands ###
