"""Add credit_balance

Revision ID: e2cf183abad9
Revises: a1df8a97c047
Create Date: 2026-03-08 06:35:45.614352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cf183abad9'
down_revision: Union[str, Sequence[str], None] = 'a1df8a97c047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalorganization', sa.Column('credit_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicalorganization', 'credit_balance')
    # ### end Alembic commands ###
